// store/interfaces/dashboard.ts

export interface Student {
    std_username: string;
    password: string;
    official_address: string | null;
    noc: string;
    other_documents: Record<string, any>;
    clc_last_college: string;
    character_certificate: string;
    academic_info: string | null;
    award_info: string | null;
    know_about_college: string | null;
    fbise_number: string;
    emergency_medication: string;
    program_applied_for: string;
    transport_fees: string;
    vehroute_id: string;
    route_id: string | null;
    vehicle_id: string | null;
    route_title: string | null;
    vehicle_no: string | null;
    room_no: string | null;
    driver_name: string | null;
    driver_contact: string | null;
    hostel_id: string | null;
    hostel_name: string | null;
    room_type_id: string | null;
    room_type: string | null;
    hostel_room_id: string;
    student_session_id: string;
    fees_discount: string;
    playlist_id: string;
    class_id: string;
    class: string;
    section_id: string;
    section: string;
    id: string;
    admission_no: string;
    roll_no: string;
    admission_date: string;
    firstname: string;
    lastname: string;
    image: string;
    mobileno: string;
    email: string | null;
    state: string | null;
    city: string | null;
    pincode: string | null;
    note: string | null;
    religion: string;
    cast: string | null;
    house_name: string | null;
    dob: string;
    birthofplace: string;
    def_status: string;
    current_address: string | null;
    previous_school: string | null;
    guardian_is: string | null;
    parent_id: string;
    student_cnic: string;
    nationality: string;
    smobno2: string;
    father_cnic: string;
    father_income: string;
    postal_address: string;
    residential_phone: string;
    last_exam_passed: string;
    exam_passing_year: string;
    obtained_marks: string;
    total_marks: string;
    name_of_board: string;
    board_roll_no: string;
    student_photograph: string;
    father_cnic_picture: string;
    student_cnic_picture: string;
    mark_sheet_picture: string;
    permanent_address: string | null;
    group: string;
    category_id: string | null;
    adhar_no: string | null;
    samagra_id: string | null;
    bank_account_no: string | null;
    bank_name: string | null;
    ifsc_code: string | null;
    guardian_name: string;
    father_pic: string | null;
    height: string | null;
    weight: string | null;
    measurement_date: string;
    mother_pic: string | null;
    guardian_pic: string | null;
    guardian_relation: string;
    guardian_phone: string;
    guardian_address: string;
    is_active: string;
    created_at: string;
    updated_at: string | null;
    father_name: string;
    father_phone: string;
    blood_group: string | null;
    school_house_id: string | null;
    father_occupation: string | null;
    mother_name: string;
    mother_phone: string;
    mother_occupation: string;
    guardian_occupation: string;
    gender: string;
    rte: string;
    guardian_email: string;
    unsuited: string;
    discount_fees: string | null;
    campus_main_id: string;
    campus: string;
    last_attended_school: string;
    percentage_last_school: string | null;
}

export interface Subject {
    id: string;
    session_id: string;
    class_section_id: string;
    campus_id: string;
    subject_id: string;
    teacher_id: string;
    class_id: string;
    description: string | null;
    is_active: string;
    created_at: string;
    updated_at: string;
    teacher_name: string;
    surname: string;
    name: string;
    type: string;
    code: string;
}

export interface SubjectData {
    student: Student;
    subjectlist: Subject[];
}

