name: Deploy to EC2 (Vite Frontend + JS Backend)

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 🔐 Setup SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

            - name: ⚙️ Install and build frontend (Vite)
              working-directory: frontend
              run: |
                  npm ci
                  npm run build

            - name: 📤 Upload Vite frontend (`dist/`) to EC2
              run: |
                  rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./frontend/dist/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/html/

            - name: 📤 Upload backend code to EC2
              run: |
                  rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./backend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PROJECT_DIR }}/backend/

            - name: 🚀 SSH into EC2 and restart backend
              run: |
                  ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
                    cd ${{ secrets.EC2_PROJECT_DIR }}/backend
                    npm ci
                    pm2 reload all || pm2 start src/index.js --name backend
                    echo "✅ Backend restarted successfully!"
                  EOF
